[package]
name = "firmware"
version = "0.1.1"
edition = "2024"
autotests = false

[[bin]]
name = "firmware"
path = "src/main.rs"
test = false
bench = false

[lib]
path = "src/lib.rs"
test = false
bench = false
doctest = false


[dependencies]
embedded-hal = "1"
nb = "1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
commitment-issues = { git = "https://github.com/dysonltd/commitment-issues" }

defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }


[dependencies.stm32f1xx-hal]
version = "0.11.0"
features = ["stm32f103", "medium"]

[build-dependencies]
commitment-issues = { git = "https://github.com/dysonltd/commitment-issues" }
