---
name: Continuous Build
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust and probe-rs
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/probe-rs/probe-rs/releases/latest/download/probe-rs-tools-installer.sh | sh
      - name: Cargo Build
        run: |
          source "$HOME"/.cargo/env
          cargo build
      - name: Cargo Build Dev
        run: |
          source "$HOME"/.cargo/env
          cargo build
